name: Trigger Discord Reviewer Ping

on:
  pull_request:
    types: [review_requested, edited]

jobs:
  extract-reviewers:
    runs-on: ubuntu-latest
    outputs:
      reviewers: ${{ steps.get-reviewers.outputs.reviewers }}
    steps:
      - name: Extract reviewers from event
        id: get-reviewers
        run: |
          event_json=$(echo '${{ toJson(github.event) }}')
          reviewers=$(echo "$event_json" | jq -r '.requested_reviewers[].login' | tr '\n' ' ')
          if [ -z "$reviewers" ]; then
            echo "No reviewers found in the event"
            exit 1
          fi
          echo "reviewers=$reviewers" >> $GITHUB_OUTPUT
          echo "Found reviewers: $reviewers"

  notify:
    needs: extract-reviewers
    uses: pusrenk/discord-action/.github/workflows/notify-reviewers.yml@main
    with:
      pr_url: ${{ github.event.pull_request.html_url }}
      reviewers: ${{ needs.extract-reviewers.outputs.reviewers }}
    secrets:
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      REVIEWER_DISCORD_MAP: ${{ secrets.REVIEWER_DISCORD_MAP }}
