name: Trigger Discord Reviewer Ping

on:
  pull_request:
    types: [review_requested]

jobs:
  notify:
    uses: pusrenk/discord-action/.github/workflows/notify-reviewers.yml@main
    with:
      pr_url: ${{ github.event.pull_request.html_url }}
      reviewers: ${{ join(github.event.requested_reviewers.*.login, ' ') }}
    secrets: inherit
